-- Active: 1774610340517@@127.0.0.1@5432@forme

CREATE TABLE IF NOT EXISTS users (
    idme UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    id VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255)NOT NULL UNIQUE,
    verified_email BOOLEAN ,
    name VARCHAR(255),
    picture VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);